-- thực tập nhóm
-- đề tài quản lý học sinh 
CREATE DATABASE QUANLYHOCSINH
GO
USE QUANLYHOCSINH
GO
CREATE TABLE HOCSINH 
(
   MAHOCSINH NCHAR(9) PRIMARY KEY,
   HOTEN NVARCHAR(50),
   GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam', N'Nữ')),
   NGAYSINH DATETIME,
   NOISINH NVARCHAR(50),
   DIACHI NVARCHAR(50),
   TONGIAO NVARCHAR(5) CHECK (TONGIAO IN (N'CÓ', N'KHÔNG'))
)
GO
CREATE TABLE GIAOVIEN
(
   MAGIAOVIEN NCHAR(9) PRIMARY KEY,
   HOTEN NVARCHAR(50),
   GTINH NVARCHAR(5) CHECK (GTINH IN (N'Nam', N'Nữ'),
   NGAYSINH DATETIME,
   NOISINH NVARCHAR(50),
   DIACHI NVARCHAR(50),
   CHUYENMON NVARCHAR(20),
   SODIENTHOAI NVARCHAR(11),
)
GO
CREATE TABLE LOP
(
   MALOP NCHAR(8) PRIMARY KEY,
   NAMHOC NVARCHAR(20),
   SISO INT,
   MA_GVCHUNHIEM NCHAR(9) REFERENCES dbo.GIAOVIEN(MAGIAOVIEN)
)
GO
CREATE TABLE KETQUAHOCTAP
(
  MAHOCSINH NCHAR(9) REFERENCES dbo.HOCSINH(MAHOCSINH),
  MALOP NCHAR(8) REFERENCES dbo.LOP(MALOP),
  DIEMTBKY1 FLOAT,
  DIEMTBKY2 FLOAT,
  DIEMTBCANAM FLOAT,
  PRIMARY KEY(MAHOCSINH,MALOP)
)
GO
CREATE TABLE MONHOC 
(
  MAMONHOC NCHAR(9) PRIMARY KEY,
  TENMONHOC NVARCHAR(30)
)
GO
CREATE TABLE KHENTHUONG 
(
  MAHOCSINH NCHAR(9) REFERENCES DBO.HOCSINH(MAHOCSINH),
  LYDO NVARCHAR(100),
  NGAY DATETIME,
  SOQD NCHAR(5)
)
GO
CREATE TABLE HANHKIEM
(
  MAHK NCHAR(9) PRIMARY KEY,
  MAHOCSINH NVAR(9) REFERENCES dbo.HOCSINH(MAHOCSINH),
  XEPLOAIHK NVARCHAR(10),
  HOCKY INT,
  NAMHOC NVARCHAR(20),
)
GO
CREATE TABLE LOP_MON 
(
  MAMONHOC NCHAR(9) REFERENCES dbo.MONHOC,
  MALOP NCHAR(8) REFERENCES dbo.LOP,
  SOTIET INT,
  PRIMARY KEY(MAMONHOC,MALOP)
)
GO
CREATE TABLE BANGDIEM
(
  MAHOCSINH NCHAR(9) REFERENCES DBO.HOCSINH(MAHOCSINH),
  MAMONHOC NCHAR(9)REFERENCES dbo.MONHOC(MAMONHOC),
  HOCKY INT,
  DIEMMIENG FLOAT,
  DIEM15PHUT FLOAT,
  DIEM1TIET FLOAT,
  DIEMHK FLOAT,
  DIEMTB FLOAT,
  PRIMARY KEY(MAHOCSINH,MAMONHOC)
)
